name: Build and deploy container app to Azure Web App - InsightGlass

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://insightglasstestserver20240517161221.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ed445907f8b54ee3a3b0fd735c8676ae }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2159967023044c5d9f48166408666857 }}
    
    - name: Convert username to lowercase
      id: lowercase_username
      run: echo "::set-output name=username::$(echo ${{ secrets.AzureAppService_ContainerUsername_ed445907f8b54ee3a3b0fd735c8676ae }} | tr '[:upper:]' '[:lower:]')"

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: insightglasstestserver20240517161221.azurecr.io/${{ steps.lowercase_username.outputs.username }}/insightglasstestserver:${{ github.sha }}
        file: ./src/InsightGlassTest/InsightGlassTest.Server/dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'InsightGlass'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9300a2d27f7a4d0b9504332da013bb58 }}
        images: 'insightglasstestserver20240517161221.azurecr.io$/{{ steps.lowercase_username.outputs.username }}/insightglasstestserver:${{ github.sha }}'
