name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        dotnet restore src/InsightGlassTest/InsightGlassTest.sln
        cd src/InsightGlassTest/insightglasstest.client
        npm install
        cd ../../..

    - name: Build the project
      run: dotnet build src/InsightGlassTest/InsightGlassTest.sln --configuration Release

    - name: Install a specific version of Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.60/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip
        sudo mv chrome-linux64 /usr/local/bin/google-chrome
        rm chrome-linux64.zip

    - name: Download and set up ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=125.0.6422.60
        wget https://storage.googleapis.com/chrome-for-testing-public/$CHROME_DRIVER_VERSION/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        rm chromedriver-linux64.zip

    - name: Run server
      run: |
        cd src/InsightGlassTest/InsightGlassTest.Server
        dotnet run --configuration Release &
        sleep 10

    - name: Run tests
      env:
        MYSQLCONNSTR_DBLiveConn: ${{ secrets.DBLiveConn }}
      run: dotnet test src/InsightGlassTest/InsightGlassTest.sln
