name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        dotnet restore src/InsightGlassTest/InsightGlassTest.sln
        cd src/InsightGlassTest/insightglasstest.client
        npm install
        cd ../../..

    - name: Build the project
      run: dotnet build src/InsightGlassTest/InsightGlassTest.sln --configuration Release

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Download and set up chromedriver
      run: |
        CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Run server
      run: |
        cd src/InsightGlassTest/InsightGlassTest.Server
        dotnet run --configuration Release &
        sleep 10

    - name: Run tests
      env:
        MYSQLCONNSTR_DBLiveConn: ${{ secrets.DBLiveConn }}
      run: dotnet test src/InsightGlassTest/InsightGlassTest.sln
